sudo: required
language: ruby
services:
  - docker
before_install:
  - docker build -t hello_docker_sinatra .
  - docker run -d -p 3000:3000 hello_docker_sinatra
  - docker ps -a
script:
  - docker run hello_docker_sinatra /bin/sh -c "bundle exec rspec"
deploy:
  provider: elasticbeanstalk
  access_key_id: xxx
  secret_access_key:
    secure: xxx
  region: us-east-1
  skip_cleanup: true
  app: hello docker sinatra
  env: helloDockerSinatra
  bucket_name: xxx
  on:
    repo: pedrocarrico/hello_docker_sinatra
    branch: master
